#
# Copyright 2022 Max Planck Institute for Software Systems, and
# National University of Singapore
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

MaxBackgroundThreads: 1
MaxCpuThreads: 5
JaegerUrl: "http://jaeger:4318/v1/traces"
#JaegerUrl: "http://localhost:4318/v1/traces"
LineBufferSize: 1
EventBufferSize: 60000000
LinuxFuncIndicator:
  - "__sys_socket"
  - "__x64_sys_socket"
  - "sock_create"
  - "__sys_bind"
  - "__x64_sys_bind"
  - "__x64_sys_connect"
  - "__sys_connect"
  - "tcp_release_cb"
  - "tcp_init_sock"
  - "tcp_init_xmit_timers"
  - "tcp_v4_connect"
  - "ip_route_output_key_hash"
  - "tcp_connect"
  - "tcp_fastopen_defer_connect"
  - "ipv4_dst_check"
  - "tcp_sync_mss"
  - "tcp_initialize_rcv_mss"
  - "tcp_write_queue_purge"
  - "tcp_clear_retrans"
  - "tcp_transmit_skb"
  - "__tcp_transmit_skb"
  - "tcp_v4_send_check"
  - "__tcp_v4_send_check"
  - "ip_queue_xmit"
  - "__ip_queue_xmit"
  - "ip_local_out"
  - "__ip_local_out"
  - "ip_output"
  - "__ip_finish_output"
  - "dev_queue_xmit"
  - "__dev_queue_xmit"
  - "skb_network_protocol"
  - "eth_type_vlan"
  - "netdev_start_xmit"
DriverFuncIndicator:
  - "i40e_features_check"
  - "i40e_lan_xmit_frame"
  - "i40e_maybe_stop_tx"
  - "vlan_get_protocol"
  - "dma_map_single_attrs"
  - "dma_map_page_attrs"
  - "i40e_maybe_stop_tx"
KernelTxIndicator:
  - "__sys_sendto"
  - "__sys_sendmsg"
  - "dev_hard_start_xmit"
  - "netdev_start_xmit"
  - "dev_queue_xmit"
KernelRxIndicator:
  #- "recvfrom"
  #- "__sys_recvmsg"
  #- "___sys_recvmsg"
  #- "__x64_sys_recvmsg"
  - "netif_receive_skb_list_internal"
  #- "ip_recv"
  #- "ip_list_rcv"
  #- "netif_receive_skb"
  #- "netif_rx"
  #- "net_rx_action"
PciWriteIndicator:
  - "pci_msix_write_vector_ctrl"
  - "__pci_write_msi_msg"
DriverTxIndicator:
  - "i40e_lan_xmit_frame"
DriverRxIndicator:
  - "i40e_napi_poll"
  - "i40e_finalize_xdp_rx"
SysEntryIndicator:
  - "entry_SYSCALL_64"
  - "error_entry"
  - "entry_SYSCALL_64_safe_stack"
BlacklistFunctions:
  - "match_strlcpy"
  - "__const_udelay"
  - "static_key_disable"
  - "__put_page"
  - "relock_page_lruvec_irqsave"
  - "xas_move_index"
  - "xas_set_offset"
  - "blk_account_io_merge_bio"
  - "biovec_phys_mergeable.isra.0"
  - "vmalloc_node"
  - "__kfifo_poke_n"
  - "__count_numa_events.isra.0"
  - "use_mwaitx_delay"
  - "orc_sort_cmp"
TypesToFilter:
  - "kHostInstrT"
  - "kSimProcInEventT"
  - "kSimSendSyncT"
  #- "kHostMmioCRT"
  #- "kHostMmioCWT"
  #- "kHostMmioImRespPoWT"
  #- "kHostMmioRT"
  #- "kHostMmioWT"
  #- "kNicMmioRT"
  #- "kNicMmioWT"
SymbolTables:
  - Identifier: "Linuxvm-Symbols"
    #Path: "/usr/src/data-folder/trace/linux_dumps/vmlinux-image-syms.dump"
    Path: "linux_dumps/vmlinux-image-syms.dump"
    AddressOffset: 0
    Type: kSyms
  - Identifier: "Nicdriver-Symbols"
    #Path: "/usr/src/data-folder/trace/linux_dumps/i40e-image-syms.dump"
    Path: "linux_dumps/i40e-image-syms.dump"
    AddressOffset: 18446744072098938880 #0xffffffffa0000000ULL
    Type: kSyms
